### ISSUE TITLE
Odd formatting for "small" descriptions

### ISSUE THREAD

**Issue by noproblemwiththat** [gnu-octave/pkg-octave-doc#13]
Hi!

I've been setting-up getting the documentation for a package of mine with GitLab pages (similar to the Github version).  That's now building, using the latest Octave and `pkg-octave-doc` from `-forge`.  Those generated docs are [here](https://jjg.gitlab.io/librtree-octave/).  For the methods with substantial documentation, the results look fine: [RTree.csv_read](https://jjg.gitlab.io/librtree-octave/RTree.csv_read.html) for example.  But for the those with minimal documentation something is awry.  The `rect_size` instance method has source
```matlab
    ## -*- texinfo -*-
    ## @deftypefn {RTree} {@var{n} =} rect_size ()
    ##
    ## The size @var{n} in bytes of a rectangle.
    ## @end deftypefn

    function val = rect_size(obj)
      val = RTree_dispatch('rect_size', obj.state);
    endfunction
```
producing

![Screenshot from 2024-01-22 23-19-07](https://github.com/gnu-octave/pkg-octave-doc/assets/130050589/ffba7303-319c-4e06-8bc2-2a39f026a3b1)

with the html being

```html
<dl>
<dt><u>RTree:</u> <var>n</var> = <b>rect_size</b><i> ()</i></dt>
</dl>

<p> The size <var>n</var> in bytes of a rectangle.
 </p><<div class="ms-5">
/dd></dl>
```
as [here](https://jjg.gitlab.io/librtree-octave/RTree.rect_size.html).

Any ideas?

**Comment by noproblemwiththat** [comment]
A bit more on this: when I add the classes to the INDEX, these stray `dd` seem to be associated with broken indentation of the methods ... https://jjg.gitlab.io/librtree-octave/RTree.html

**Comment by pr0m1th3as** [comment]
Can you remove the empty line between texinfo and the function as in the example below and rebuild the documentation and post the result here to see whether it makes a difference or not? The following example is parsed properly with the documentation page shown [here](https://gnu-octave.github.io/statistics/ConfusionMatrixChart.html)
````
## -*- texinfo -*-
    ## @deftypefn  {ConfusionMatrixChart} {} disp (@var{cmc}, @var{order})
    ## Display the properties of the @code{ConfusionMatrixChart} object
    ## @var{cmc}.
    ##
    ## @end deftypefn
    function disp (this)
      nv_sizes = size (this.NormalizedValues);
      cl_sizes = size (this.ClassLabels);

      printf ("%s with properties:\n\n", class (this));
      printf ("\tNormalizedValues: [ %dx%d %s ]\n", nv_sizes(1), nv_sizes(2),...
        class (this.NormalizedValues));
      printf ("\tClassLabels: { %dx%d %s }\n\n", cl_sizes(1), cl_sizes(2),...
        class (this.ClassLabels));
    endfunction
````

**Comment by noproblemwiththat** [comment]
Ah!

In fact the issue is not the blank line between comment and function (I did try that, but made no difference), but the "blank comment-line" before the `@end deftypefn`, so with

```matlab
    ## -*- texinfo -*-
    ## @deftypefn {RTree} {@var{n} =} branch_size ()
    ##
    ## The size @var{n} in bytes of a branch.
    ##
    ## @end deftypefn

    function val = branch_size(obj)
      val = RTree_dispatch('branch_size', obj.state);
    endfunction
```
I get

![Screenshot from 2024-01-23 10-02-15](https://github.com/gnu-octave/pkg-octave-doc/assets/130050589/01318fca-a6d5-4506-834f-b99144361a1d)

That also fixes the indentation issues I mention in "single page class" comment above.  

Strange that this only occurs with small documentation though, I note that examples on the [Octave wiki page](https://wiki.octave.org/Classdef) which have big documentation don't consistently use this penultimate blank comment.

In any case, many thanks! -- do please close this now.

**Comment by pr0m1th3as** [comment]
I am glad this has been resolved, although I am not sure why this happens only with small texts. Most likely it relates to docstrings with single sentence being parsed differently by `texi2html` software. I will add this in the Guidelines section of the README so that others can benefit from and avoid this issue.
