### ISSUE TITLE
Improve error message when texi2html is missing

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/pkg-octave-doc#4]
From this:
```
package_texi2html("doctest")
error: function_texi2html: unable to convert to html.
error: called from
    function_texi2html at line 132 column 5
    package_texi2html at line 268 column 7
```
and the README, I was able to guess what was wrong, but maybe it could give a clear error message.

Perhaps "texi2html command-line tool is missing, see documentation"?

**Comment by pr0m1th3as** [comment]
Updated function to address this issue
