### ISSUE TITLE
error: bd_tag(1): out of bound 0 (dimensions are 0x0)

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/pkg-octave-doc#5]
```
>>> package_texi2html("pkg-octave-doc")
error: bd_tag(1): out of bound 0 (dimensions are 0x0)
error: called from
    function_texi2html at line 148 column 29
    package_texi2html at line 268 column 7
```
And I got the same error for other packages I tried (`doctest`, `image`, `symbolic`).

OS is Fedora 37, Octave 7.2.0, texi2html installed from Fedora package:
```
$ texi2html --version
5.0
```

**Comment by pr0m1th3as** [comment]
This error has to do with `texi2html` version. I have updated `function_texi2html` to check for required version (1.8.2) and handling certain tags that produce error (@abbr -> @asis) or are not identified (@qcode -> @code)

**Comment by cbm755** [comment]
I have a hard time reconciling mine (version 5) with 1.8.2...  Is there perhaps more than one texi2html in wild?

**Comment by cbm755** [comment]
I found this: looks like 8 years ago Fedora bumped from version 1.82 (not clear to me if 1.8.2 or 1.82) to 5.0.

**Comment by cbm755** [comment]
Forgot link: https://src.fedoraproject.org/rpms/texi2html/c/06be27a0dc63f7553e7bec96fafe5ef0a87bb798?branch=rawhide

**Comment by cbm755** [comment]
OTOH, Ubuntu 20.04 and 22.04 seem to stay with the 1.82:
```
$ podman pull ubuntu:22.04
$ podman run -it --rm ubuntu:22.04
# apt list texi2html
Listing... Done
texi2html/jammy 1.82+dfsg1-6 all
```

**Comment by pr0m1th3as** [comment]
I am on Ubuntu, hence the 1.82 version, but you should be able to install this version in Fedora as well
