### ISSUE TITLE
reliably trimming the "generated on <date> using <blah>"

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/pkg-octave-doc#6]
Is this code supposed to find the "real body" of the output, stripping the "generated on blah by blah"?
```
    ## Remove content before <body> tag and after <hr size="1">
    txt_beg = strfind (fcn_text, "<body ");
    txt_end = strfind (fcn_text, "<hr size=""1"">") - 1;
    fcn_text = fcn_text([txt_beg:txt_end]);
```

Using `texi2html` 5.0  from Fedora (see also #5), I have:

```
<p> @seealso{function_texi2html, find_GHurls, build_DEMOS}
 </p></dd></dl>
<hr>
<p>
 <font size="-1">
  This document was generated on <i>February 21, 2023</i> using <a href="http://www.nongnu.org/texi2html/"><i>texi2html 5.0</i></a>.
 </font>
 <br>

</p>
</body>
</html>
```

I tried this and it seems to work:
```
    txt_end = strfind (fcn_text, "<hr>\n<p>\n <font size=""-1"">") - 1
```

But this all feels a bit fragile...  version-specific...

Did you see an option in texi2html to suppress that that output?

**Comment by cbm755** [comment]
I looked in the `generate_html` source, looks like it was done like this:

```
  ## Add easily recognisable text before and after real text
  start = "###### OCTAVE START ######";
  stop  = "###### OCTAVE STOP ######";
  text = sprintf ("%s\n%s\n%s\n", start, text, stop);
```

Is that better than what I did in #8?

**Comment by pr0m1th3as** [comment]
I think it is best to search for `</p></dd></dl>` as the end of the desired output.
At least this is what I do in `function_texi2html`

**Comment by pr0m1th3as** [comment]
Check the latest commit https://github.com/gnu-octave/pkg-octave-doc/commit/e3056fc2685491f90f559c1f7acea7db13349f57 if it works ok with `texi2html` v5.0
