### ISSUE TITLE
extra newlines compared to `generate_html` pkg

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/pkg-octave-doc#9]
(note this was done with texi2html 5.0, #8 so it could be b/c of that...

Here a screenshot of the generated docs for `doctest`, where I have highlighted part of the text:

![image](https://user-images.githubusercontent.com/818622/220448327-dc6de0c4-c909-4777-9751-11161423a605.png)

If I compare to that made with `generate_html`, I don't see those extra newlines:

https://octave.sourceforge.io/doctest/function/doctest.html

**Comment by pr0m1th3as** [comment]
It must be related to texti2html version 5. IMO we should stick with 1.82 version, which it is frozen and thus there will be no formatting issues with a future release. My approach is that I make some changes to certain tags that version 1.82 does not recognize (e.g. @abbr -> @asis, @qcode -> @code) and then apply some post processing to the HTML output (e.g. handle @seealso tag by adding urls for listed functions that belong to the same package)
